package org.xiyu.reforged.core;

import com.mojang.logging.LogUtils;
import org.slf4j.Logger;

import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * ModDescriptorConverter — Converts NeoForge's {@code neoforge.mods.toml} to
 * Forge's {@code mods.toml} format via string manipulation.
 *
 * <h3>Key conversions:</h3>
 * <ul>
 *     <li>{@code loaderVersion="[4,)"} → {@code loaderVersion="[52,)"}</li>
 *     <li>{@code modId="neoforge"} dependency → {@code modId="forge"}</li>
 *     <li>{@code type="required"} → {@code mandatory=true}</li>
 *     <li>NeoForge version ranges → Forge version ranges</li>
 *     <li>Adds a dependency on {@code reforged} mod</li>
 * </ul>
 */
public final class ModDescriptorConverter {

    private static final Logger LOGGER = LogUtils.getLogger();
    public static final String REFORGED_DISCOVERY_MARKER = "# Auto-generated by ReForged for Forge discovery only";

    // Target platform: Forge 1.21 / 51.x.
    private static final String FORGE_LOADER_VERSION = "[51,)";
    private static final String FORGE_VERSION_RANGE = "[51,)";

    /**
     * Convert a NeoForge {@code neoforge.mods.toml} content string to
     * Forge-compatible {@code mods.toml} content.
     *
     * @param neoContent the original neoforge.mods.toml content
     * @return the converted mods.toml content
     */
    public static String convert(String neoContent) {
        String result = neoContent;

        // 1. Replace loaderVersion (NeoForge uses ~[4,), Forge uses [52,))
        result = replaceValue(result, "loaderVersion", "\"" + FORGE_LOADER_VERSION + "\"");

        // 2. Replace neoforge dependency with forge
        result = result.replace("modId=\"neoforge\"", "modId=\"forge\"");
        result = result.replace("modId = \"neoforge\"", "modId = \"forge\"");

        // 3. Replace neoforge version ranges in dependency blocks
        // NeoForge version ranges like [21.1,) → Forge ranges [52,)
        result = replaceNeoForgeVersionRange(result);

        // 4. Convert type="required" → mandatory=true  (NeoForge 1.21.1 format)
        result = result.replace("type=\"required\"", "mandatory=true");
        result = result.replace("type = \"required\"", "mandatory = true");
        result = result.replace("type=\"optional\"", "mandatory=false");
        result = result.replace("type = \"optional\"", "mandatory = false");
        result = result.replace("type=\"incompatible\"", "mandatory=false");
        result = result.replace("type = \"incompatible\"", "mandatory = false");
        result = result.replace("type=\"discouraged\"", "mandatory=false");
        result = result.replace("type = \"discouraged\"", "mandatory = false");

        // 5. Remove NeoForge-specific keys that Forge doesn't understand
        result = removeLines(result, "enumExtensions");
        // Remove 'reason' key in dependency blocks (NeoForge-only)
        result = removeLines(result, "reason=");
        result = removeLines(result, "reason =");

        // 6. Extract all mod IDs for adding reforged dependency
        List<String> modIds = extractModIds(result);

        // 7. Append reforged dependency for each mod
        StringBuilder sb = new StringBuilder(result);
        for (String modId : modIds) {
            sb.append("\n\n# Auto-added by ReForged — ensures shim classes are available\n");
            sb.append("[[dependencies.\"").append(modId).append("\"]]\n");
            sb.append("modId=\"reforged\"\n");
            sb.append("mandatory=true\n");
            sb.append("versionRange=\"[1.0.0,)\"\n");
            sb.append("ordering=\"BEFORE\"\n");
            sb.append("side=\"BOTH\"\n");
        }
        result = sb.toString();

        LOGGER.info("[ReForged] ModDescriptorConverter: Converted neoforge.mods.toml " +
                "({} mod(s): {})", modIds.size(), modIds);

        return result;
    }

    /**
     * Returns true when a NeoForge dependency block explicitly rejects ReForged.
     * The declaration is scoped to the dependency block so an unrelated
     * {@code type = "incompatible"} entry cannot disable the mod accidentally.
     */
    public static boolean declaresReForgedIncompatibility(String neoContent) {
        Pattern blockPattern = Pattern.compile(
                "(?ms)^\\s*\\[\\[dependencies(?:\\.\\\"[^\\\"]+\\\"|\\.[^\\]]+)\\]\\].*?(?=^\\s*\\[\\[|\\z)");
        Matcher blocks = blockPattern.matcher(neoContent);
        while (blocks.find()) {
            String block = blocks.group();
            String modId = firstTomlValue(block, "modId");
            String type = firstTomlValue(block, "type");
            if ("reforged".equalsIgnoreCase(modId) && "incompatible".equalsIgnoreCase(type)) {
                return true;
            }
        }
        return false;
    }

    private static String firstTomlValue(String block, String key) {
        Pattern valuePattern = Pattern.compile("(?m)^\\s*" + Pattern.quote(key)
                + "\\s*=\\s*[\\\"']([^\\\"']+)[\\\"']");
        Matcher value = valuePattern.matcher(block);
        return value.find() ? value.group(1).trim() : "";
    }

    /**
     * Build a minimal Forge descriptor that lets Forge's own mod-folder scanner
     * accept a NeoForge jar without executing it through JavaFML.
     *
     * <p>The real NeoForge code is still loaded by ReForged's dynamic loader from
     * {@code neoforge.mods.toml}. This discovery descriptor intentionally strips
     * NeoForge mixin/access-transformer declarations and uses {@code lowcodefml}
     * so Forge records the mod id for dependency checks but does not instantiate
     * the NeoForge entrypoint a second time.</p>
     */
    public static String convertForForgeDiscovery(String neoContent) {
        List<ModMetadata> mods = extractModMetadata(neoContent);
        if (mods.isEmpty()) {
            mods = List.of(new ModMetadata("unknown_neoforge_mod", "0.0.0",
                    "Unknown NeoForge Mod", "NeoForge mod discovered by ReForged."));
        }

        StringBuilder sb = new StringBuilder();
        sb.append(REFORGED_DISCOVERY_MARKER).append('\n');
        sb.append("modLoader=\"lowcodefml\"\n");
        sb.append("loaderVersion=\"").append(FORGE_LOADER_VERSION).append("\"\n");
        sb.append("license=").append(quoteToml(firstValue(neoContent, "license").orElse("UNKNOWN"))).append("\n\n");

        for (ModMetadata mod : mods) {
            sb.append("[[mods]]\n");
            sb.append("modId=").append(quoteToml(mod.modId())).append('\n');
            sb.append("version=").append(quoteToml(mod.version())).append('\n');
            sb.append("displayName=").append(quoteToml(mod.displayName())).append('\n');
            sb.append("description=").append(quoteToml(mod.description())).append("\n\n");
        }

        LOGGER.info("[ReForged] ModDescriptorConverter: Generated Forge discovery metadata for {} NeoForge mod(s): {}",
                mods.size(), mods.stream().map(ModMetadata::modId).toList());
        return sb.toString();
    }

    // ─── Internal helpers ──────────────────────────────────────────

    /**
     * Replace a TOML key's value. Handles both quoted and unquoted values.
     */
    private static String replaceValue(String content, String key, String newValue) {
        // Match: key = "..." or key="..."
        Pattern p = Pattern.compile("(" + Pattern.quote(key) + "\\s*=\\s*)\"[^\"]*\"");
        Matcher m = p.matcher(content);
        if (m.find()) {
            return m.replaceAll("$1" + Matcher.quoteReplacement(newValue));
        }
        return content;
    }

    /**
     * Replace NeoForge-specific version ranges in dependency blocks.
     * Looks for versionRange values that look like NeoForge versions (e.g., [21.1,))
     * and replaces them with Forge equivalents.
     */
    private static String replaceNeoForgeVersionRange(String content) {
        // Find lines with versionRange after a neoforge→forge dependency
        // Simple approach: replace version ranges that look like NeoForge ranges
        // NeoForge uses versions like 21.x, Forge uses 52.x for 1.21.1
        String result = content;

        // Replace NeoForge version ranges (21.x pattern)
        result = result.replaceAll(
                "(versionRange\\s*=\\s*)\"\\[21\\.[^\"]*\"",
                "$1\"" + FORGE_VERSION_RANGE + "\"");

        // Also handle [20.x, [1.x (older NeoForge patterns)
        result = result.replaceAll(
                "(versionRange\\s*=\\s*)\"\\[20\\.[^\"]*\"",
                "$1\"" + FORGE_VERSION_RANGE + "\"");

        return result;
    }

    /**
     * Remove entire lines containing a specific key.
     */
    private static String removeLines(String content, String key) {
        return content.replaceAll("(?m)^.*" + Pattern.quote(key) + ".*$\\n?", "");
    }

    /**
     * Extract all modId values from [[mods]] sections.
     */
    private static List<String> extractModIds(String content) {
        List<String> ids = new ArrayList<>();
        Pattern p = Pattern.compile("modId\\s*=\\s*\"([^\"]+)\"");
        Matcher m = p.matcher(content);
        boolean inModsSection = false;
        for (String line : content.split("\n")) {
            String trimmed = line.trim();
            if (trimmed.equals("[[mods]]")) {
                inModsSection = true;
                continue;
            }
            if (trimmed.startsWith("[[") && !trimmed.equals("[[mods]]")) {
                inModsSection = false;
            }
            if (inModsSection) {
                Matcher lm = p.matcher(trimmed);
                if (lm.find()) {
                    ids.add(lm.group(1));
                    inModsSection = false;
                }
            }
        }
        if (ids.isEmpty()) {
            // Fallback: grab first modId anywhere
            Matcher fm = p.matcher(content);
            if (fm.find()) ids.add(fm.group(1));
        }
        return ids;
    }

    private record ModMetadata(String modId, String version, String displayName, String description) {}

    private static List<ModMetadata> extractModMetadata(String content) {
        List<ModMetadata> mods = new ArrayList<>();
        String[] lines = content.split("\\R");
        boolean inModsSection = false;
        String modId = null;
        String version = null;
        String displayName = null;
        String description = null;

        for (String line : lines) {
            String trimmed = line.trim();
            if (trimmed.equals("[[mods]]")) {
                if (modId != null) {
                    mods.add(toMetadata(modId, version, displayName, description));
                }
                inModsSection = true;
                modId = null;
                version = null;
                displayName = null;
                description = null;
                continue;
            }
            if (trimmed.startsWith("[[") && !trimmed.equals("[[mods]]")) {
                if (inModsSection && modId != null) {
                    mods.add(toMetadata(modId, version, displayName, description));
                }
                inModsSection = false;
                modId = null;
                version = null;
                displayName = null;
                description = null;
                continue;
            }
            if (!inModsSection) {
                continue;
            }

            if (modId == null) modId = valueOnLine(trimmed, "modId").orElse(null);
            if (version == null) version = valueOnLine(trimmed, "version").orElse(null);
            if (displayName == null) displayName = valueOnLine(trimmed, "displayName").orElse(null);
            if (description == null) description = valueOnLine(trimmed, "description").orElse(null);
        }

        if (inModsSection && modId != null) {
            mods.add(toMetadata(modId, version, displayName, description));
        }
        return mods;
    }

    private static ModMetadata toMetadata(String modId, String version, String displayName, String description) {
        String safeId = (modId == null || modId.isBlank()) ? "unknown_neoforge_mod" : modId.trim();
        String safeVersion = (version == null || version.isBlank()) ? "0.0.0" : version.trim();
        String safeName = (displayName == null || displayName.isBlank()) ? safeId : displayName.trim();
        String safeDescription = (description == null || description.isBlank())
                ? "NeoForge mod discovered by ReForged."
                : description.trim();
        return new ModMetadata(safeId, safeVersion, safeName, safeDescription);
    }

    private static java.util.Optional<String> firstValue(String content, String key) {
        for (String line : content.split("\\R")) {
            java.util.Optional<String> value = valueOnLine(line.trim(), key);
            if (value.isPresent()) return value;
        }
        return java.util.Optional.empty();
    }

    private static java.util.Optional<String> valueOnLine(String line, String key) {
        Pattern p = Pattern.compile("^" + Pattern.quote(key) + "\\s*=\\s*(.+?)(?:\\s+#.*)?$");
        Matcher m = p.matcher(line);
        if (!m.find()) return java.util.Optional.empty();
        String raw = m.group(1).trim();
        if ((raw.startsWith("\"") && raw.endsWith("\"")) || (raw.startsWith("'") && raw.endsWith("'"))) {
            raw = raw.substring(1, raw.length() - 1);
        }
        if (raw.startsWith("'''")) {
            raw = raw.substring(3);
        }
        return java.util.Optional.of(raw);
    }

    private static String quoteToml(String value) {
        String escaped = value == null ? "" : value
                .replace("\\", "\\\\")
                .replace("\"", "\\\"")
                .replace("\r", "")
                .replace("\n", "\\n");
        return "\"" + escaped + "\"";
    }
}
