package org.xiyu.reforged.core;

import com.mojang.logging.LogUtils;
import org.slf4j.Logger;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.jar.JarEntry;
import java.util.jar.JarFile;

/**
 * Discovers NeoForge mod JARs from the mods directory, classpath, and module path.
 *
 * <p>A NeoForge mod JAR is identified by having {@code META-INF/neoforge.mods.toml}.
 * Dual-platform jars with their own Forge descriptor are left to Forge; jars whose
 * Forge descriptor was generated by ReForged are still dynamically loaded from the
 * NeoForge descriptor.</p>
 */
public final class NeoJarDiscovery {

    private static final Logger LOGGER = LogUtils.getLogger();

    private NeoJarDiscovery() {}

    /**
     * Find JARs in modsDir that should be loaded through the NeoForge bridge.
     */
    public static List<Path> discoverNeoForgeJars(Path modsDir) {
        List<Path> result = new ArrayList<>();
        try (var stream = Files.list(modsDir)) {
            for (Path path : stream.filter(p -> p.toString().endsWith(".jar")).sorted().toList()) {
                try (JarFile jar = new JarFile(path.toFile())) {
                    if (shouldBridgeNeoForgeJar(jar, path)) {
                        result.add(bridgeSourceFor(jar, path));
                    }
                } catch (Exception e) {
                    LOGGER.debug("[ReForged] Skipping {}: {}", path.getFileName(), e.getMessage());
                }
            }
        } catch (Exception e) {
            LOGGER.error("[ReForged] Error scanning mods directory", e);
        }
        return result;
    }

    /**
     * Scan the Java classpath for NeoForge mod JARs.
     *
     * <p>In a development environment (ForgeGradle {@code runClient}), mods added as
     * {@code runtimeOnly} dependencies in {@code build.gradle} end up on the classpath
     * rather than in the {@code mods/} directory. This method discovers them by
     * checking each classpath entry for {@code META-INF/neoforge.mods.toml}.</p>
     *
     * @return list of NeoForge mod JAR paths found on the classpath
     */
    public static List<Path> discoverNeoForgeJarsOnClasspath() {
        List<Path> result = new ArrayList<>();
        try {
            String classpath = System.getProperty("java.class.path", "");
            if (classpath.isEmpty()) return result;

            String[] entries = classpath.split(System.getProperty("path.separator", ":"));
            LOGGER.debug("[ReForged] Scanning {} classpath entries for NeoForge mods", entries.length);

            for (String entry : entries) {
                if (!entry.endsWith(".jar")) continue;

                Path path = Path.of(entry);
                if (!Files.isRegularFile(path)) continue;

                String fileName = path.getFileName().toString().toLowerCase(Locale.ROOT);
                if (isCommonLibrary(fileName)) {
                    continue;
                }

                try (JarFile jar = new JarFile(path.toFile())) {
                    if (shouldBridgeNeoForgeJar(jar, path)) {
                        result.add(bridgeSourceFor(jar, path));
                        LOGGER.debug("[ReForged] Classpath NeoForge mod: {}", path);
                    }
                } catch (Exception e) {
                    // Not a valid JAR - skip.
                }
            }

            String modulePath = System.getProperty("jdk.module.path", "");
            if (!modulePath.isEmpty()) {
                for (String entry : modulePath.split(System.getProperty("path.separator", ":"))) {
                    if (!entry.endsWith(".jar")) continue;
                    Path path = Path.of(entry);
                    if (!Files.isRegularFile(path)) continue;

                    try (JarFile jar = new JarFile(path.toFile())) {
                        if (shouldBridgeNeoForgeJar(jar, path)) {
                            result.add(bridgeSourceFor(jar, path));
                            LOGGER.debug("[ReForged] Module-path NeoForge mod: {}", path);
                        }
                    } catch (Exception e) {
                        // Not a valid JAR - skip.
                    }
                }
            }

            try {
                Path workDir = Path.of(System.getProperty("user.dir", "."));
                Path[] extraDirs = {
                        workDir.resolve("build/fg_cache"),
                        workDir.resolve("build/libraries"),
                        workDir.resolve(".gradle/loom-cache"),
                };
                for (Path dir : extraDirs) {
                    if (Files.isDirectory(dir)) {
                        try (var walk = Files.walk(dir, 5)) {
                            walk.filter(p -> p.toString().endsWith(".jar"))
                                    .filter(Files::isRegularFile)
                                    .forEach(p -> {
                                        try (JarFile jar = new JarFile(p.toFile())) {
                                            if (shouldBridgeNeoForgeJar(jar, p)) {
                                                result.add(bridgeSourceFor(jar, p));
                                                LOGGER.debug("[ReForged] Build-cache NeoForge mod: {}", p);
                                            }
                                        } catch (Exception e) {
                                            // Not a valid JAR - skip.
                                        }
                                    });
                        }
                    }
                }
            } catch (Exception e) {
                LOGGER.debug("[ReForged] Extra directory scan failed: {}", e.getMessage());
            }

        } catch (Exception e) {
            LOGGER.debug("[ReForged] Classpath scan failed: {}", e.getMessage());
        }
        return result;
    }

    private static boolean isCommonLibrary(String fileName) {
        return fileName.startsWith("forge-") || fileName.startsWith("minecraft-")
                || fileName.startsWith("client-") || fileName.startsWith("reforged")
                || fileName.contains("asm-") || fileName.contains("mixin-")
                || fileName.contains("guava-") || fileName.contains("gson-")
                || fileName.contains("log4j-") || fileName.contains("slf4j-")
                || fileName.contains("nightconfig-") || fileName.contains("jopt-simple");
    }

    private static boolean shouldBridgeNeoForgeJar(JarFile jar, Path path) {
        boolean hasNeo = jar.getJarEntry("META-INF/neoforge.mods.toml") != null;
        if (!hasNeo) return false;

        try (var input = jar.getInputStream(jar.getJarEntry("META-INF/neoforge.mods.toml"))) {
            if (ModDescriptorConverter.declaresReForgedIncompatibility(
                    new String(input.readAllBytes(), StandardCharsets.UTF_8))) {
                LOGGER.info("[ReForged] Skipping author-excluded NeoForge JAR {}", path.getFileName());
                return false;
            }
        } catch (java.io.IOException e) {
            throw new IllegalStateException("Cannot read NeoForge metadata: " + path, e);
        }

        JarEntry forgeToml = jar.getJarEntry("META-INF/mods.toml");
        if (forgeToml == null) return true;

        if (isReForgedDiscoveryDescriptor(jar, forgeToml)) {
            LOGGER.debug("[ReForged] Loading patched NeoForge JAR {} through bridge", path.getFileName());
            return true;
        }

        LOGGER.info("[ReForged] Skipping dual-platform JAR {} - has both mods.toml and neoforge.mods.toml, letting Forge handle it",
                path.getFileName());
        return false;
    }

    private static Path bridgeSourceFor(JarFile jar, Path path) {
        JarEntry forgeToml = jar.getJarEntry("META-INF/mods.toml");
        if (forgeToml != null && isReForgedDiscoveryDescriptor(jar, forgeToml)) {
            Path backup = path.resolveSibling(path.getFileName() + ".neoforge-original");
            if (Files.isRegularFile(backup)) {
                LOGGER.debug("[ReForged] Using original NeoForge backup for dynamic loading: {}", backup.getFileName());
                return backup;
            }
        }
        return path;
    }

    private static boolean isReForgedDiscoveryDescriptor(JarFile jar, JarEntry forgeToml) {
        try (var input = jar.getInputStream(forgeToml)) {
            String content = new String(input.readAllBytes(), StandardCharsets.UTF_8);
            return content.contains(ModDescriptorConverter.REFORGED_DISCOVERY_MARKER);
        } catch (Exception e) {
            return false;
        }
    }
}
